// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI3jygwiR_eo7Q3TJejvM3ByJAL1xirBk',
    appId: '1:260559848797:android:760de78e9d9c28bbe4d4b4',
    messagingSenderId: '260559848797',
    projectId: 'flxmarket-6664b',
    storageBucket: 'flxmarket-6664b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwLQ4OX8sWLctAbBwPbPCvLPqVNv7__6A',
    appId: '1:260559848797:ios:52c79168db4d8ce8e4d4b4',
    messagingSenderId: '260559848797',
    projectId: 'flxmarket-6664b',
    storageBucket: 'flxmarket-6664b.firebasestorage.app',
    iosClientId: '260559848797-uh8btimkrt34v6m1ha2iuk62a8l244tp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flxMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9QzjWOPQ4CTqu7TA-FAU_u9jQC9HzcPc',
    appId: '1:295411715838:web:b9cf7ea61fc74daac79faf',
    messagingSenderId: '295411715838',
    projectId: 'service-reservation-system',
    authDomain: 'service-reservation-system.firebaseapp.com',
    storageBucket: 'service-reservation-system.firebasestorage.app',
    measurementId: 'G-J7PCKF42KV',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABydUu63sPTiI5D8X4HhDigh1pVRYlUDI',
    appId: '1:260559848797:web:0b73bcb3254795b4e4d4b4',
    messagingSenderId: '260559848797',
    projectId: 'flxmarket-6664b',
    authDomain: 'flxmarket-6664b.firebaseapp.com',
    storageBucket: 'flxmarket-6664b.firebasestorage.app',
    measurementId: 'G-70JLJN6SCC',
  );

}